name: Deploy

on:
  push:
    branches:
      - 'main'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.1
          architecture: x64
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        run: flake8
  deploy:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Copy Dockerfile
        run: cp docker/rpi2/Dockerfile app/Dockerfile
      - name: Balena Deploy
        uses: bekriebel/balena-cli-action@v1
        if: success()
        with:
          balena_api_token: ${{secrets.BALENA_API_TOKEN}}
          application_path: "app/"
          balena_command: "push ${{secrets.BALENA_APPLICATION_NAME}} --logs"