name: Deploy Develop

on:
  push:
    branches:
      - 'develop'

jobs:
  lint_and_test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.4
          architecture: x64
      - name: Checkout source code
        uses: actions/checkout@master
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run flake8
        run: flake8
      - name: Run mypy
        run: mypy .
      - name: Run Pytest
        run: pytest
  deploy_develop:
    name: Deploy Develop
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout source code
        uses: actions/checkout@master
      - name: Copy Dockerfile
        run: cp docker/rpi3/Dockerfile .
      - name: Balena Deploy
        uses: bartoszadamczyk/balena-cli-action@v1
        if: success()
        with:
          balena_api_token: ${{secrets.BALENA_API_TOKEN}}
          application_path: "."
          balena_command: "push ${{secrets.BALENA_APPLICATION_NAME_RPI_2}} --logs"