name: Deploy

on:
  push:
    branches:
      - 'main'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.1
          architecture: x64
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        run: flake8
  deploy:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v1
    - name: Copy Dockerfile
      run: cp docker/rpi2/Dockerfile app/Dockerfile
    - name: Deploy to balena
      uses: bartoszadamczyk/balena-push@v1.0.0
      with:
        api-token: ${{secrets.BALENA_API_TOKEN}}
        application-name: ${{secrets.BALENA_APPLICATION_NAME}}
        application-path: "./app"